intervals:
  base-url: https://intervals.icu
  client-id: ${INTERVALS_CLIENT_ID}

capacnan:
  buckets:
    credentials: claviger
    maps-activities: tabula-rogeriana-intervals-activities
  streams:
    maps:
      name: tabula-rogeriana

quarkus:
  devservices:
    enabled: false
  rest-client:
    intervals-v1:
      url: ${intervals.base-url}
  messaging:
    nats:
      connection:
        servers:
          - "nats://localhost:4222"

'%dev':
  quarkus:
    rest-client:
      intervals-v1:
        logging:
          scope: all
          body-limit: 10240
    log:
#      level: DEBUG
      category:
        "io.quarkus.rest.client.reactive":
          level: DEBUG