intervals:
  base-url: https://intervals.icu
  client-id: ${INTERVALS_CLIENT_ID}

quarkus:
  devservices:
    enabled: false
  config:
    locations:
      - "${CAPACNAN_BLUEPRINT_ROOT_URI:}"
      - "${CAPACNAN_BLUEPRINT_CREDENTIALS_URI:}"
      - "${CAPACNAN_BLUEPRINT_GEO_URI:}"
  rest-client:
    intervals-v1:
      url: ${intervals.base-url}
  messaging:
    nats:
      connection:
        servers:
          - "nats://localhost:4222"

'%dev':
  quarkus:
    rest-client:
      intervals-v1:
        logging:
          scope: all
          body-limit: 10240
    log:
#      level: DEBUG
      category:
        "io.quarkus.rest.client.reactive":
          level: DEBUG